### ISSUE TITLE
using rest for promote

### ISSUE THREAD

**Issue by romanman** [heroku/heroku-pipeline#18]
Hey Guys ,

We are using some rest apis to call heroku cli commans as show releases and rolllback, is it possible to call the same way to 'promote' ?

**Comment by ryanbrainard** [comment]
It is possible, but the promote API is not publicly documented and may change at any time.

**Comment by romanman** [comment]
@ryanbrainard : thanks for the good news. I will be following after the changes so don't mind to try it. Can you please post the concrete calls structure?

**Comment by ryanbrainard** [comment]
@romanman I forgot to mention it earlier, but your best bet to do what `pipeline:promote` does via REST is to use the Releases API directly (`pipeline:promote` uses this internally). Here is an article about it:

https://devcenter.heroku.com/articles/platform-api-copying-slugs

and the full documentation:
https://devcenter.heroku.com/articles/platform-api-reference#release

**Comment by romanman** [comment]
Thanks, I'll try it

**Comment by romanman** [comment]
Thanks
